version: "3.9"
services:
  bot:
    build: .
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - TZ=${TZ:-Europe/Amsterdam}
      - DB_PATH=/app/data/bot.db
    volumes:
      - ./data:/app/data
